[package]
name = "promobase"
version = "0.1.0"
edition = "2021"

[dependencies]
tauri = { version = "2.0.0", features = ["shell-open"] }
tauri-plugin-sql = { version = "2.0.0", features = ["sqlite"] }

[build-dependencies]
tauri-build = { version = "2.0.0" }

